### ISSUE TITLE
Moon-phase Incompatibility with B3M (Вращение Земли Майнкрафтская - Accurate day/night-cycles Mod ) mod 

### ISSUE THREAD

**Issue by Fireztonez** [Tfarcenim/darkness#4]
**My Issue:**
Hello, I really enjoy the idea to have darker night depending of the moon phase, and your mod do an amasing job for that function.

On my modpack I have the B3M mod question to have longuer day's than normal. but for some reason, your mod can't get the moon phase. So right now all night is completly black, like if it is New-Moon each night... I don't know if you can add compatibility to that mod with the B3M API or possibly add option to set directly the day/night cycle time to your mod or create a another mod for that for 1.16.5.

**Java Version:** 1.8.0_281
**Minecraft Forge:** 1.16.5-36.0.42 

**Total Darkness Version:** 1.2
**B3M version: ** 1.16.4-02   --> ( https://www.curseforge.com/minecraft/mc-mods/time-speed-mod )

B3M API: https://github.com/Sedridor/B3M/wiki/ModAPI

Thank's
Fireztonez

**Comment by Tfarcenim** [comment]
I will add compat only if it doesn't require a compile time dependency.

**Comment by Tfarcenim** [comment]
This looks like a disaster
